app:
  short-host: https://f200.co/
micronaut:
  server:
    port: 8082
  application:
    name: urlshortner
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
redis:
  uri:   # read from env variable, this is hosted in cloud
  password: # read from env variable, this is hosted in cloud
  expiry: 2628288 # expiry of record in seconds (~30days if url is not expanded)
netty:
  default:
    allocator:
      max-order: 3
